# Generated by Django 3.2 on 2023-06-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblalumno',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblalumnohorario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblapoderado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblcargo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblcolegio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblempleado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblempleadohonorario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblformapago',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblgrado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblmovilidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblmovilidadpago',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblmovilidadruta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblparentesco',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbltipomantenimiento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblvehiculo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblvehiculodocumento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblvehiculogasto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblvehiculomantenimiento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblzona',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'managed': True},
        ),
    ]
